# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientFetcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=20)),
                ('lastActive', models.DateField()),
            ],
        ),
    ]
